name: model-training
on: [push]
jobs:
  report:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      - name: 'Train my model'
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          jupyter kernelspec list
          python makereport.py
          cml-send-comment report.output.md
